Scale head slot correctly for small armor stand
GeyserMC/GeyserOptionalPack pull request #33
Opened 2022-08-07 03:58 UTC by Kas-tle

Allows for proper scaling of head slot for small armor stand.

See related PR on Geyser:

https://github.com/GeyserMC/Geyser/pull/3210

[GeyserOptionalPack.zip](https://github.com/GeyserMC/GeyserOptionalPack/files/9276159/GeyserOptionalPack.zip)

2022-08-07 22:37 UTC, davchoo commented
This pack seems to work for helmets, but causes `player_head`, `skeleton_skull`, and `carved_pumpkin` to appear way too large. In addition, it seems to have no effect on banners in the head slot.

(Left is Java, Right is Bedrock 1.19.11)
![screenshot](https://user-images.githubusercontent.com/4722249/183313490-b0add1b5-fad1-4e5f-97be-5f398733a7e9.png)

2022-08-07 22:46 UTC, Kas-tle commented
@davchoo this is not the cause; that occurs without any pack. We discussed somewhat in discord but basically though we'd like to fix this with optionalpack, we cannot.

2022-08-10 21:33 UTC, davchoo requested changes
Besides the typos in the documentation, this PR works fine. Helmets, skulls, and carved_pumpkins seems to be scaled correctly with this pack.

2022-08-10 21:33 UTC, davchoo commented on developer_documentation.md
> +Geyser scales down small armor stands to 0.5. However, this has the unintended side effect of making the head slot appear smaller than it does on Java Edition. Consequently, the query `q.is_baby` is
Some typos.
derrived -> derived
spplied -> applied
occuring -> occuring

2022-08-10 22:05 UTC, Camotoy approved these changes

2022-08-10 22:05 UTC, merged